#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Koma Tsutsumi
# SPDX-License-Identifier: GPL-3.0-only

import sys

numbers = []

for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    try:
        numbers.append(float(line))
    except ValueError:
        continue

avg = sum(numbers) / len(numbers)
print(avg)

