#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 Koma Tsutsumi
# SPDX-License-Identifier: GPL-3.0-only

import sys

args = sys.argv[1:]  


total = 0.0
count = 0

for a in args:
    total += float(a)
    count += 1

print(total / count)

